<?php

$auth['autorisation_page'] = "/user/auth/"; /* Страница авторизации */
$auth['session_page'] = "/main/sessionActive/"; /* Страница Сессии */
$auth['no_redirect'] = array("/index.php/user/auth/",
    "/index.php/api_java/api_upd_application/",
    "/index.php/api_java/api_insert_application/",
    "/index.php/api_java/getProgrammData/",
    "/index.php/api_java/api_update_prem/",
    "/index.php/api_java/api_list_application/",
    "/index.php/api_java/api_list_programms/",
    "/index.php/api_java/api_is_user/",
    "/index.php/api_fias/fias/",
    "/index.php/api_java/api_insert_sms/",
    "/index.php/main/drupal_module/",
    "/index.php/api_java/get_itog/",
    "/index.php/api_java/get_all_recording/",
    "/index.php/apixml/set_xml/",
    "/index.php/apixml/get_xml_by_id/",
    "/index.php/apixml/get_new_id/",
    "/index.php/apiProgramm/getAllProgramm/",
    "/index.php/apiProgramm/getAllRegion/",
    "/index.php/apiProgramm/getAllUsers/",
    "/index.php/main/login/",
    "/index.php/main/getUsersByLoginCode/",
    "/index.php/main/get_programms",
    "/index.php/main/getMessege/",
    "/index.php/main/getUsersByLoginCode",
    "/index.php/cron/getTTLogin/",
    "/index.php/cron/croneAction/",
    "/index.php/grotemAPI/getPrograms",
    "/index.php/grotemAPI/getProgramLine",
    "/index.php/grotemAPI/setProgramm",
    "/index.php/grotemAPI/getInstalledPrograms",
    "/index.php/Reconciliation/getDailyReconciliation",
    "/index.php/Reconciliation/setStatus",
    "/index.php/Reconciliation/getXml",
    "/index.php/Main/testSetApp",
    "/index.php/main/sessionActive/",
    "/index.php/main/sessionActive",
    "/index.php/Reconciliation/getInformation",
    "/index.php/Apicalc/getProgramm",
    "/index.php/ApiLk/getData",
    "/index.php/ApiLk/getTemplate",
    "/index.php/ApiLk/getStatus",
    "/index.php/ApiLk/getFileList",
    "/index.php/ApiLk/getFile",
    "/index.php/ApiLk/enterSms",

); /* Страницы с которых не нужен редирект на авторизацию */

$config['auth'] = $auth;
